language:
  - swift
osx_image: xcode11.2
xcode_project: DiffValue.xcodeproj # path to your xcodeproj folder
xcode_scheme: DiffValue
script:
  - xcodebuild -scheme DiffValue -sdk iphonesimulator build test ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
