language:
  - swift
osx_image: xcode11.2
script:
  - xcodebuild -scheme DiffValue -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.2' build test ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

